CREATE TABLE dbo.cadastro 
(
    CPF VARCHAR2(11) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    ALIMENTO VARCHAR(50) NOT NULL,   
)

ALTER TABLE dbo.cadastro
  ADD CONSTRAINT CPF_PK PRIMARY KEY (
    CPF
  )
/